title: Henry Guerrero- Duarte's Portfolio of Cybersecurity Projects
description: To show case my amazing skills to my future employers
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
