title: Henry Guerrero- Duarte's Portfolio of Cybersecurity Projects
description: To showcase my amazing skills to my future employers
show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
